#!/usr/bin/env node
// Generate a deterministic large-scale .tmodel fixture for stress-testing
// the GUI at HAYST-realistic factor counts (~100 factors, ~4 levels each).
//
// Usage:
//   node scripts/genLargeFixture.mjs [factors] [outputPath]
//
// Defaults: 100 factors → examples/large-100.tmodel
//
// The output is deterministic (no Math.random) so the fixture can be
// regenerated and diffed reliably.

import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const factorCount = Number.parseInt(process.argv[2] ?? '100', 10)
const outputPath = process.argv[3] ?? `examples/large-${factorCount}.tmodel`

// Linear-congruential generator (seedable, deterministic across Node versions).
function makeRng(seed) {
  let state = seed >>> 0
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0
    return state / 0x100000000
  }
}

const rng = makeRng(42)

const FACTOR_GROUPS = [
  'Auth', 'Payment', 'Search', 'Cart', 'Checkout', 'Profile', 'Notification',
  'Catalog', 'Inventory', 'Shipping', 'Tax', 'Discount', 'Loyalty', 'Review',
  'Wishlist', 'Recommendation', 'Tracking', 'Refund', 'Subscription', 'Report',
]

const LEVEL_TEMPLATES = [
  ['enabled', 'disabled', 'partial', 'forced'],
  ['v1', 'v2', 'v3', 'v4', 'legacy'],
  ['low', 'medium', 'high'],
  ['JP', 'US', 'EU', 'APAC', 'global'],
  ['sync', 'async', 'queued'],
  ['cached', 'fresh', 'stale', 'invalid'],
  ['admin', 'user', 'guest', 'service'],
  ['draft', 'published', 'archived'],
  ['onPrem', 'cloud', 'hybrid', 'edge'],
  ['fast', 'normal', 'slow'],
  ['retry', 'fail', 'fallback', 'skip'],
  ['JSON', 'XML', 'CSV', 'binary'],
]

function pick(arr) {
  return arr[Math.floor(rng() * arr.length)]
}

function pickLevels() {
  const tpl = pick(LEVEL_TEMPLATES)
  const target = 3 + Math.floor(rng() * 3) // 3..5 levels, avg ≈ 4
  if (tpl.length >= target) return tpl.slice(0, target)
  // pad with synthetic levels
  const out = [...tpl]
  while (out.length < target) out.push(`opt${out.length + 1}`)
  return out
}

const factors = []
const usedNames = new Set()
for (let i = 0; i < factorCount; i++) {
  let name
  do {
    name = `${pick(FACTOR_GROUPS)}${String(i + 1).padStart(3, '0')}Mode`
  } while (usedNames.has(name))
  usedNames.add(name)
  factors.push({ name, levels: pickLevels() })
}

// Synthesize a handful of constraints across distant factors to exercise
// the propagation slice suggester. ~10% of factors participate.
const constraints = []
const constraintCount = Math.max(5, Math.floor(factorCount / 10))
for (let i = 0; i < constraintCount; i++) {
  const a = factors[Math.floor(rng() * factors.length)]
  let b = factors[Math.floor(rng() * factors.length)]
  while (b.name === a.name) b = factors[Math.floor(rng() * factors.length)]
  const aLevel = pick(a.levels)
  const bLevel = pick(b.levels)
  constraints.push(
    `IF [${a.name}] = "${aLevel}" THEN [${b.name}] <> "${bLevel}";`,
  )
}

const lines = []
lines.push(`# NeoCombi stress-test fixture: ${factorCount} factors, ~4 levels each.`)
lines.push(`# Generated by scripts/genLargeFixture.mjs (seed=42, deterministic).`)
lines.push(`# Goal: validate GUI scrolling / perf at HAYST-realistic scale.`)
lines.push('')
const widest = factors.reduce((w, f) => Math.max(w, f.name.length), 0)
for (const f of factors) {
  lines.push(`${f.name.padEnd(widest)}: ${f.levels.join(', ')}`)
}
lines.push('')
lines.push(`# ${constraintCount} synthetic constraints (cross-factor).`)
for (const c of constraints) lines.push(c)
lines.push('')

const out = lines.join('\n')
const path = resolve(process.cwd(), outputPath)
await writeFile(path, out, 'utf8')
process.stdout.write(
  `Wrote ${factorCount} factors, ${constraintCount} constraints → ${outputPath}\n`,
)
