// GENERATED by 'npm run build:pict-core' from src/engines/dsl — do not edit.

// src/engines/dsl/lexer.ts
var KEYWORDS = {
  IF: "kw_if",
  THEN: "kw_then",
  ELSE: "kw_else",
  AND: "kw_and",
  OR: "kw_or",
  NOT: "kw_not",
  IN: "kw_in",
  LIKE: "kw_like"
};
function lex(source) {
  const tokens = [];
  let line = 1;
  let lineStart = 0;
  let i = 0;
  const here = () => ({
    line,
    column: i - lineStart + 1,
    offset: i
  });
  const peek = (offset = 0) => source[i + offset] ?? "";
  while (i < source.length) {
    const ch = source[i];
    if (ch === " " || ch === "	") {
      i++;
      continue;
    }
    if (ch === "\r" || ch === "\n") {
      const start = here();
      if (ch === "\r" && peek(1) === "\n") {
        i += 2;
      } else {
        i++;
      }
      const end = here();
      tokens.push({
        kind: "newline",
        text: source.slice(start.offset, i),
        range: { start, end }
      });
      line++;
      lineStart = i;
      continue;
    }
    if (ch === "#") {
      while (i < source.length && source[i] !== "\n" && source[i] !== "\r") {
        i++;
      }
      continue;
    }
    if (ch === '"') {
      const start = here();
      i++;
      let value = "";
      while (i < source.length && source[i] !== '"') {
        const c = source[i];
        if (c === "\\" && i + 1 < source.length) {
          const next = source[i + 1];
          if (next === "\\") {
            value += "\\";
            i += 2;
          } else if (next === '"') {
            value += '"';
            i += 2;
          } else if (next === "n") {
            value += "\n";
            i += 2;
          } else if (next === "t") {
            value += "	";
            i += 2;
          } else {
            value += c;
            i++;
          }
        } else if (c === "\n" || c === "\r") {
          break;
        } else {
          value += c;
          i++;
        }
      }
      if (i < source.length && source[i] === '"') {
        i++;
      }
      const end = here();
      tokens.push({
        kind: "string",
        text: source.slice(start.offset, i),
        value,
        range: { start, end }
      });
      continue;
    }
    if (isDigit(ch)) {
      const start = here();
      while (i < source.length && isDigit(source[i])) i++;
      if (source[i] === "." && isDigit(peek(1))) {
        i++;
        while (i < source.length && isDigit(source[i])) i++;
      }
      const end = here();
      const text = source.slice(start.offset, i);
      tokens.push({
        kind: "number",
        text,
        value: Number(text),
        range: { start, end }
      });
      continue;
    }
    if (ch === "-" && isDigit(peek(1)) && canStartValue(tokens)) {
      const start = here();
      i++;
      while (i < source.length && isDigit(source[i])) i++;
      if (source[i] === "." && isDigit(peek(1))) {
        i++;
        while (i < source.length && isDigit(source[i])) i++;
      }
      const end = here();
      const text = source.slice(start.offset, i);
      tokens.push({
        kind: "number",
        text,
        value: Number(text),
        range: { start, end }
      });
      continue;
    }
    const startPos = here();
    if (ch === ":") {
      i++;
      tokens.push({ kind: "colon", text: ":", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === ",") {
      i++;
      tokens.push({ kind: "comma", text: ",", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === ";") {
      i++;
      tokens.push({ kind: "semicolon", text: ";", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "{") {
      i++;
      tokens.push({ kind: "lbrace", text: "{", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "}") {
      i++;
      tokens.push({ kind: "rbrace", text: "}", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "[") {
      i++;
      tokens.push({ kind: "lbracket", text: "[", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "]") {
      i++;
      tokens.push({ kind: "rbracket", text: "]", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "(") {
      i++;
      tokens.push({ kind: "lparen", text: "(", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === ")") {
      i++;
      tokens.push({ kind: "rparen", text: ")", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "=") {
      i++;
      tokens.push({ kind: "eq", text: "=", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "~") {
      i++;
      tokens.push({ kind: "tilde", text: "~", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "@") {
      i++;
      tokens.push({ kind: "at", text: "@", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === "<") {
      if (peek(1) === "=") {
        i += 2;
        tokens.push({ kind: "lte", text: "<=", range: { start: startPos, end: here() } });
        continue;
      }
      if (peek(1) === ">") {
        i += 2;
        tokens.push({ kind: "neq", text: "<>", range: { start: startPos, end: here() } });
        continue;
      }
      i++;
      tokens.push({ kind: "lt", text: "<", range: { start: startPos, end: here() } });
      continue;
    }
    if (ch === ">") {
      if (peek(1) === "=") {
        i += 2;
        tokens.push({ kind: "gte", text: ">=", range: { start: startPos, end: here() } });
        continue;
      }
      i++;
      tokens.push({ kind: "gt", text: ">", range: { start: startPos, end: here() } });
      continue;
    }
    if (isIdHead(ch)) {
      const start = here();
      i++;
      while (i < source.length && isIdMid(source[i])) i++;
      const end = here();
      const text = source.slice(start.offset, i);
      const upper = text.toUpperCase();
      const kw = KEYWORDS[upper];
      if (kw !== void 0) {
        tokens.push({ kind: kw, text, range: { start, end } });
      } else {
        tokens.push({
          kind: "identifier",
          text,
          value: text,
          range: { start, end }
        });
      }
      continue;
    }
    const unkStart = here();
    i++;
    tokens.push({
      kind: "unknown",
      text: ch,
      range: { start: unkStart, end: here() }
    });
  }
  const eofPos = here();
  tokens.push({
    kind: "eof",
    text: "",
    range: { start: eofPos, end: eofPos }
  });
  return tokens;
}
function isDigit(ch) {
  return ch >= "0" && ch <= "9";
}
function isIdHead(ch) {
  if (!ch) return false;
  return ch >= "A" && ch <= "Z" || ch >= "a" && ch <= "z" || ch === "_" || ch.codePointAt(0) > 127;
}
function isIdMid(ch) {
  if (!ch) return false;
  return isIdHead(ch) || isDigit(ch);
}
function canStartValue(tokens) {
  if (tokens.length === 0) return true;
  const prev = tokens[tokens.length - 1];
  switch (prev.kind) {
    case "eq":
    case "neq":
    case "gt":
    case "gte":
    case "lt":
    case "lte":
    case "comma":
    case "lbrace":
    case "lparen":
    case "colon":
    case "kw_then":
    case "kw_else":
    case "kw_in":
    case "newline":
      return true;
    default:
      return false;
  }
}

// src/engines/dsl/maskLevel.ts
var MASK_LEVEL = "_MASK_";
function isMaskLevel(value) {
  return typeof value === "string" && value === MASK_LEVEL;
}
function isMaskLevelNode(level) {
  return (level.type === "identifier" || level.type === "string") && level.value === MASK_LEVEL;
}

// src/engines/dsl/validator.ts
function validateModel(model) {
  const diagnostics = [];
  const factorsByName = /* @__PURE__ */ new Map();
  for (const p of model.parameters) factorsByName.set(p.name, p);
  for (const c of model.constraints) {
    walkConstraintPredicates(c, (predicate) => {
      if (predicate.type === "comparison") {
        validateComparison(predicate, factorsByName, diagnostics);
      } else if (predicate.type === "in") {
        validateInClause(predicate, factorsByName, diagnostics);
      }
    });
  }
  validateMaskLevelBindings(model, diagnostics);
  return diagnostics;
}
function validateMaskLevelBindings(model, out) {
  const factorsWithMask = model.parameters.filter(
    (p) => p.levels.some(isMaskLevelNode)
  );
  if (factorsWithMask.length === 0) return;
  const boundFactors = /* @__PURE__ */ new Set();
  for (const c of model.constraints) {
    walkConstraintPredicates(c, (predicate) => {
      if (predicate.type === "comparison" && predicate.op === "=" && (predicate.right.type === "string" || predicate.right.type === "identifier") && predicate.right.value === MASK_LEVEL) {
        boundFactors.add(predicate.left.name);
      } else if (predicate.type === "in") {
        const includesMask = predicate.values.some(
          (v) => (v.type === "string" || v.type === "identifier") && v.value === MASK_LEVEL
        );
        if (includesMask) boundFactors.add(predicate.left.name);
      }
    });
  }
  for (const factor of factorsWithMask) {
    if (boundFactors.has(factor.name)) continue;
    const maskNode = factor.levels.find(isMaskLevelNode);
    out.push({
      severity: "warning",
      kind: "unbound-mask-level",
      message: `Factor [${factor.name}] has a _MASK_ level, but the constraint clause for it is missing or incomplete. You need to specify both: under what conditions the factor becomes _MASK_, and that it must not be _MASK_ otherwise.`,
      range: maskNode.range
    });
  }
}
function walkConstraintPredicates(c, visit) {
  if (c.type === "if") {
    walkPredicate(c.condition, visit);
    walkPredicate(c.then, visit);
    if (c.else) walkPredicate(c.else, visit);
  } else {
    walkPredicate(c.predicate, visit);
  }
}
function walkPredicate(p, visit) {
  visit(p);
  switch (p.type) {
    case "and":
    case "or":
      walkPredicate(p.left, visit);
      walkPredicate(p.right, visit);
      return;
    case "not":
      walkPredicate(p.operand, visit);
      return;
  }
}
function validateComparison(cmp, factors, out) {
  const lhs = factors.get(cmp.left.name);
  if (!lhs) {
    out.push(unknownParameterDiagnostic(cmp.left));
    return;
  }
  if (cmp.right.type === "paramRef") {
    if (!factors.has(cmp.right.name)) {
      out.push(unknownParameterDiagnostic(cmp.right));
    }
    return;
  }
  if (cmp.op !== "=" && cmp.op !== "<>") return;
  if (!literalIsDeclaredLevel(lhs, cmp.right)) {
    out.push(unknownLevelDiagnostic(lhs, cmp.right));
  }
}
function validateInClause(inc, factors, out) {
  const lhs = factors.get(inc.left.name);
  if (!lhs) {
    out.push(unknownParameterDiagnostic(inc.left));
    return;
  }
  for (const v of inc.values) {
    if (!literalIsDeclaredLevel(lhs, v)) {
      out.push(unknownLevelDiagnostic(lhs, v));
    }
  }
}
function literalIsDeclaredLevel(factor, literal) {
  const target = String(literal.value);
  for (const lv of factor.levels) {
    if (String(lv.value) === target) return true;
  }
  return false;
}
function unknownParameterDiagnostic(ref) {
  return {
    severity: "error",
    kind: "unknown-parameter",
    message: `Parameter [${ref.name}] is not declared`,
    range: ref.range
  };
}
function unknownLevelDiagnostic(factor, literal) {
  const declared = factor.levels.map((lv) => String(lv.value)).join(", ");
  return {
    severity: "error",
    kind: "unknown-level",
    message: `Level "${String(literal.value)}" is not declared on factor [${factor.name}] (declared: ${declared})`,
    range: literal.range
  };
}

// src/engines/dsl/parser.ts
function parse(source) {
  const tokens = lex(source);
  const parser = new Parser(tokens);
  const result = parser.parse();
  if (result.model) {
    const semantic = validateModel(result.model);
    if (semantic.length > 0) {
      return {
        model: result.model,
        diagnostics: [...result.diagnostics, ...semantic]
      };
    }
  }
  return result;
}
var Parser = class {
  tokens;
  pos;
  diagnostics;
  constructor(tokens) {
    this.tokens = tokens;
    this.pos = 0;
    this.diagnostics = [];
  }
  parse() {
    const parameters = [];
    const constraints = [];
    while (!this.atEnd()) {
      this.skipNewlines();
      if (this.atEnd()) break;
      const t = this.peek();
      if (t.kind === "identifier" && this.lookaheadHasColonBeforeNewline()) {
        const decl = this.parseParameterDecl();
        if (decl) parameters.push(decl);
        continue;
      }
      if (t.kind === "kw_if" || t.kind === "kw_not" || t.kind === "lbracket" || t.kind === "lparen") {
        const c = this.parseConstraint();
        if (c) constraints.push(c);
        continue;
      }
      if (t.kind === "lbrace") {
        this.report(
          "unsupported-mvp",
          "Submodel notation '{ ... } @ N' is not supported in MVP",
          t.range,
          "See DSL_Grammar_Specification.md \xA77.2"
        );
        this.skipToNextStatement();
        continue;
      }
      if (t.kind === "at") {
        this.report(
          "unsupported-mvp",
          "Submodel order operator '@' is not supported in MVP",
          t.range,
          "See DSL_Grammar_Specification.md \xA77.2"
        );
        this.skipToNextStatement();
        continue;
      }
      if (t.kind === "tilde") {
        this.report(
          "unsupported-mvp",
          "Negative value marker '~' is not supported in MVP",
          t.range,
          "See DSL_Grammar_Specification.md \xA77.2"
        );
        this.advance();
        continue;
      }
      this.report(
        "syntax",
        `Unexpected ${describe(t)} at top level`,
        t.range
      );
      this.advance();
    }
    return {
      model: { parameters, constraints },
      diagnostics: this.diagnostics
    };
  }
  // ---------------------------------------------------------------------------
  // Parameter declarations
  // ---------------------------------------------------------------------------
  parseParameterDecl() {
    const nameToken = this.expect("identifier", "Expected parameter name");
    if (!nameToken) {
      this.skipToNextStatement();
      return null;
    }
    let name = nameToken.text;
    let nameEndRange = nameToken.range;
    while (this.peek().kind === "identifier") {
      const next = this.advance();
      name += " " + next.text;
      nameEndRange = next.range;
    }
    if (!this.expect("colon", "Expected ':' after parameter name")) {
      this.skipToNextStatement();
      return null;
    }
    const levels = [];
    const first = this.parseLevel();
    if (first) levels.push(first);
    while (this.match("comma")) {
      const lv = this.parseLevel();
      if (lv) levels.push(lv);
    }
    const lastRange = levels[levels.length - 1]?.range ?? nameToken.range;
    const decl = {
      type: "parameter",
      name,
      range: { start: nameToken.range.start, end: lastRange.end },
      nameRange: { start: nameToken.range.start, end: nameEndRange.end },
      levels
    };
    while (!this.atEnd() && this.peek().kind !== "newline" && this.peek().kind !== "eof") {
      const stray = this.advance();
      this.report(
        "syntax",
        `Unexpected ${describe(stray)} after parameter declaration`,
        stray.range
      );
    }
    return decl;
  }
  parseLevel() {
    const t = this.peek();
    if (t.kind === "tilde") {
      this.advance();
      this.report(
        "unsupported-mvp",
        "Negative value marker '~' is not supported in MVP",
        t.range,
        "See DSL_Grammar_Specification.md \xA77.2"
      );
      return this.parseLevel();
    }
    if (t.kind === "string") {
      this.advance();
      return {
        type: "string",
        value: typeof t.value === "string" ? t.value : t.text,
        range: t.range
      };
    }
    if (t.kind === "number") {
      this.advance();
      return {
        type: "number",
        value: typeof t.value === "number" ? t.value : Number(t.text),
        raw: t.text,
        range: t.range
      };
    }
    if (t.kind === "identifier") {
      this.advance();
      if (this.peek().kind === "lparen" && this.tokens[this.pos + 1]?.kind === "number" && this.tokens[this.pos + 2]?.kind === "rparen") {
        const lp = this.advance();
        this.advance();
        const rp = this.advance();
        this.report(
          "unsupported-mvp",
          "Level weight '(N)' is not supported in MVP",
          { start: lp.range.start, end: rp.range.end },
          "See DSL_Grammar_Specification.md \xA77.2"
        );
      }
      return { type: "identifier", value: t.text, range: t.range };
    }
    this.report(
      "syntax",
      `Expected level value, got ${describe(t)}`,
      t.range
    );
    return null;
  }
  // ---------------------------------------------------------------------------
  // Constraints
  // ---------------------------------------------------------------------------
  parseConstraint() {
    const t = this.peek();
    if (t.kind === "kw_if") {
      return this.parseIfStatement();
    }
    return this.parseUnconditionalConstraint();
  }
  parseIfStatement() {
    const ifToken = this.expect("kw_if", "Expected IF");
    if (!ifToken) return null;
    const condition = this.parsePredicate();
    if (!this.expect("kw_then", "Expected THEN")) {
      this.skipToNextStatement();
      return null;
    }
    const thenBranch = this.parsePredicate();
    let elseBranch = null;
    if (this.match("kw_else")) {
      elseBranch = this.parsePredicate();
    }
    const semi = this.expect("semicolon", "Expected ';' to terminate IF / THEN constraint");
    const endRange = semi?.range ?? (elseBranch ?? thenBranch ?? condition)?.range ?? ifToken.range;
    if (!condition || !thenBranch) {
      this.skipToNextStatement();
      return null;
    }
    return {
      type: "if",
      condition,
      then: thenBranch,
      else: elseBranch,
      range: { start: ifToken.range.start, end: endRange.end }
    };
  }
  parseUnconditionalConstraint() {
    const start = this.peek().range.start;
    const predicate = this.parsePredicate();
    const semi = this.expect("semicolon", "Expected ';' to terminate constraint");
    const endRange = semi?.range ?? predicate?.range;
    if (!predicate || !endRange) {
      this.skipToNextStatement();
      return null;
    }
    return {
      type: "unconditional",
      predicate,
      range: { start, end: endRange.end }
    };
  }
  // ---------------------------------------------------------------------------
  // Predicate (precedence: OR < AND < NOT < atomic)
  // ---------------------------------------------------------------------------
  parsePredicate() {
    return this.parseOrExpr();
  }
  parseOrExpr() {
    let left = this.parseAndExpr();
    while (left && this.peek().kind === "kw_or") {
      this.advance();
      const right = this.parseAndExpr();
      if (!right) return left;
      left = {
        type: "or",
        left,
        right,
        range: { start: left.range.start, end: right.range.end }
      };
    }
    return left;
  }
  parseAndExpr() {
    let left = this.parseNotExpr();
    while (left && this.peek().kind === "kw_and") {
      this.advance();
      const right = this.parseNotExpr();
      if (!right) return left;
      left = {
        type: "and",
        left,
        right,
        range: { start: left.range.start, end: right.range.end }
      };
    }
    return left;
  }
  parseNotExpr() {
    if (this.peek().kind === "kw_not") {
      const notTok = this.advance();
      const operand = this.parseNotExpr();
      if (!operand) return null;
      return {
        type: "not",
        operand,
        range: { start: notTok.range.start, end: operand.range.end }
      };
    }
    return this.parseAtomicPredicate();
  }
  parseAtomicPredicate() {
    const t = this.peek();
    if (t.kind === "lparen") {
      this.advance();
      const inner = this.parsePredicate();
      if (!this.expect("rparen", "Expected ')'")) {
        return inner;
      }
      return inner;
    }
    if (t.kind === "lbracket") {
      return this.parseComparisonOrIn();
    }
    this.report(
      "syntax",
      `Expected predicate, got ${describe(t)}`,
      t.range
    );
    this.advance();
    return null;
  }
  parseComparisonOrIn() {
    const left = this.parseParameterRef();
    if (!left) return null;
    const op = this.peek();
    if (op.kind === "kw_in") {
      return this.parseInClauseRest(left);
    }
    if (op.kind === "kw_like") {
      this.advance();
      this.report(
        "unsupported-mvp",
        "LIKE operator is not supported in MVP",
        op.range,
        "See DSL_Grammar_Specification.md \xA77.2"
      );
      if (this.peek().kind === "string" || this.peek().kind === "identifier") {
        this.advance();
      }
      return null;
    }
    const cmp = compareOpFromToken(op);
    if (cmp === null) {
      this.report(
        "syntax",
        `Expected relation operator, got ${describe(op)}`,
        op.range
      );
      return null;
    }
    this.advance();
    const right = this.parseValueOrRef();
    if (!right) return null;
    return {
      type: "comparison",
      left,
      op: cmp,
      right,
      range: { start: left.range.start, end: right.range.end }
    };
  }
  parseInClauseRest(left) {
    this.expect("kw_in", "Expected IN");
    if (!this.expect("lbrace", "Expected '{' after IN")) return null;
    const values = [];
    if (this.peek().kind !== "rbrace") {
      const first = this.parseValueLiteral();
      if (first) values.push(first);
      while (this.match("comma")) {
        const v = this.parseValueLiteral();
        if (v) values.push(v);
      }
    }
    const close = this.expect("rbrace", "Expected '}' to close IN { ... }");
    if (!close) return null;
    return {
      type: "in",
      left,
      values,
      range: { start: left.range.start, end: close.range.end }
    };
  }
  parseParameterRef() {
    const lb = this.expect("lbracket", "Expected '['");
    if (!lb) return null;
    const first = this.expect("identifier", "Expected parameter name inside '[ ]'");
    if (!first) return null;
    let name = first.text;
    while (this.peek().kind === "identifier") {
      name += " " + this.advance().text;
    }
    const rb = this.expect("rbracket", "Expected ']'");
    if (!rb) return null;
    return {
      type: "paramRef",
      name,
      range: { start: lb.range.start, end: rb.range.end }
    };
  }
  parseValueOrRef() {
    if (this.peek().kind === "lbracket") {
      return this.parseParameterRef();
    }
    return this.parseValueLiteral();
  }
  parseValueLiteral() {
    const t = this.peek();
    if (t.kind === "tilde") {
      this.advance();
      this.report(
        "unsupported-mvp",
        "Negative value marker '~' is not supported in MVP",
        t.range,
        "See DSL_Grammar_Specification.md \xA77.2"
      );
      return this.parseValueLiteral();
    }
    if (t.kind === "string") {
      this.advance();
      return {
        type: "string",
        value: typeof t.value === "string" ? t.value : t.text,
        range: t.range
      };
    }
    if (t.kind === "number") {
      this.advance();
      return {
        type: "number",
        value: typeof t.value === "number" ? t.value : Number(t.text),
        raw: t.text,
        range: t.range
      };
    }
    if (t.kind === "identifier") {
      this.advance();
      this.report(
        "syntax",
        `Constraint values must be quoted strings or numbers; got bare identifier "${t.text}". Wrap it: "${t.text}".`,
        t.range,
        "See DSL_Grammar_Specification.md \xA74 (Value rule)."
      );
      return null;
    }
    this.report(
      "syntax",
      `Expected value (quoted string or number), got ${describe(t)}`,
      t.range
    );
    return null;
  }
  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------
  peek(offset = 0) {
    return this.tokens[this.pos + offset] ?? this.tokens[this.tokens.length - 1];
  }
  advance() {
    const t = this.tokens[this.pos];
    if (this.pos < this.tokens.length - 1) this.pos++;
    return t;
  }
  match(kind) {
    if (this.peek().kind === kind) {
      this.advance();
      return true;
    }
    return false;
  }
  /** Expect a token kind. On match advance and return; otherwise emit syntax error and return null. */
  expect(kind, message) {
    if (this.peek().kind === kind) {
      return this.advance();
    }
    const t = this.peek();
    this.report("syntax", `${message} (got ${describe(t)})`, t.range);
    return null;
  }
  report(kind, message, range, hint) {
    this.diagnostics.push({
      severity: "error",
      kind,
      message,
      range,
      ...hint !== void 0 ? { hint } : {}
    });
  }
  atEnd() {
    return this.peek().kind === "eof";
  }
  skipNewlines() {
    while (this.peek().kind === "newline") {
      this.advance();
    }
  }
  /** Skip until the next likely statement boundary (newline / `;` / EOF). */
  skipToNextStatement() {
    while (!this.atEnd() && this.peek().kind !== "newline" && this.peek().kind !== "semicolon") {
      this.advance();
    }
    if (this.peek().kind === "newline" || this.peek().kind === "semicolon") {
      this.advance();
    }
  }
  /**
   * Lookahead helper for the parameter / constraint section dispatch.
   * Returns true iff there is a `:` token before the next newline / EOF
   * (without consuming any tokens).
   */
  lookaheadHasColonBeforeNewline() {
    let j = this.pos;
    while (j < this.tokens.length) {
      const t = this.tokens[j];
      if (t.kind === "newline" || t.kind === "eof") return false;
      if (t.kind === "colon") return true;
      j++;
    }
    return false;
  }
};
function compareOpFromToken(t) {
  switch (t.kind) {
    case "eq":
      return "=";
    case "neq":
      return "<>";
    case "gt":
      return ">";
    case "gte":
      return ">=";
    case "lt":
      return "<";
    case "lte":
      return "<=";
    default:
      return null;
  }
}
function describe(t) {
  switch (t.kind) {
    case "eof":
      return "end of input";
    case "newline":
      return "newline";
    case "identifier":
      return `identifier '${t.text}'`;
    case "string":
      return `string ${t.text}`;
    case "number":
      return `number ${t.text}`;
    case "unknown":
      return `unknown character '${t.text}'`;
    default:
      return `'${t.text}'`;
  }
}

// src/engines/dsl/evaluator.ts
var DEFAULT_ENUMERATION_LIMIT = 1e6;
function buildTypeInfo(model) {
  const factors = model.parameters.map((p) => {
    const isAllNumeric = p.levels.length > 0 && p.levels.every((l) => l.type === "number");
    const type = isAllNumeric ? "numeric" : "string";
    const levels = p.levels.map((l) => levelNodeValue(l, type));
    return { name: p.name, type, levels };
  });
  const byName = /* @__PURE__ */ new Map();
  for (const f of factors) byName.set(f.name, f);
  return { factors, byName };
}
function levelNodeValue(node, type) {
  if (type === "numeric") {
    return typeof node.value === "number" ? node.value : Number(node.value);
  }
  return String(node.value);
}
function evalPredicate(p, assignment, info) {
  switch (p.type) {
    case "or":
      return evalPredicate(p.left, assignment, info) || evalPredicate(p.right, assignment, info);
    case "and":
      return evalPredicate(p.left, assignment, info) && evalPredicate(p.right, assignment, info);
    case "not":
      return !evalPredicate(p.operand, assignment, info);
    case "comparison":
      return evalComparison(p, assignment, info);
    case "in":
      return evalIn(p, assignment, info);
  }
}
function evalComparison(c, assignment, info) {
  const leftFactor = info.byName.get(c.left.name);
  if (!leftFactor) return false;
  const leftValue = assignment[c.left.name];
  if (leftValue === void 0) return false;
  let rightValue;
  if (c.right.type === "paramRef") {
    const rf = info.byName.get(c.right.name);
    if (!rf) return false;
    rightValue = assignment[c.right.name];
  } else {
    rightValue = literalValueAs(c.right, leftFactor.type);
  }
  if (rightValue === void 0) return false;
  return compareValues(leftValue, c.op, rightValue, leftFactor.type);
}
function evalIn(e, assignment, info) {
  const factor = info.byName.get(e.left.name);
  if (!factor) return false;
  const lhs = assignment[e.left.name];
  if (lhs === void 0) return false;
  for (const v of e.values) {
    const rhs = literalValueAs(v, factor.type);
    if (rhs === void 0) continue;
    if (equals(lhs, rhs, factor.type)) return true;
  }
  return false;
}
function literalValueAs(node, factorType) {
  if (factorType === "numeric") {
    if (typeof node.value === "number") return node.value;
    const n = Number(node.value);
    return Number.isFinite(n) ? n : void 0;
  }
  return String(node.value);
}
function compareValues(a, op, b, factorType) {
  if (factorType === "numeric") {
    const na = typeof a === "number" ? a : Number(a);
    const nb = typeof b === "number" ? b : Number(b);
    if (!Number.isFinite(na) || !Number.isFinite(nb)) return false;
    switch (op) {
      case "=":
        return na === nb;
      case "<>":
        return na !== nb;
      case ">":
        return na > nb;
      case ">=":
        return na >= nb;
      case "<":
        return na < nb;
      case "<=":
        return na <= nb;
    }
  }
  const sa = String(a);
  const sb = String(b);
  switch (op) {
    case "=":
      return sa === sb;
    case "<>":
      return sa !== sb;
    case ">":
      return sa > sb;
    case ">=":
      return sa >= sb;
    case "<":
      return sa < sb;
    case "<=":
      return sa <= sb;
  }
}
function equals(a, b, factorType) {
  return compareValues(a, "=", b, factorType);
}
function isConstraintSatisfied(c, assignment, info) {
  if (c.type === "if") {
    return isIfSatisfied(c, assignment, info);
  }
  return isUnconditionalSatisfied(c, assignment, info);
}
function isIfSatisfied(c, assignment, info) {
  const cond = evalPredicate(c.condition, assignment, info);
  if (cond) {
    return evalPredicate(c.then, assignment, info);
  }
  if (c.else) {
    return evalPredicate(c.else, assignment, info);
  }
  return true;
}
function isUnconditionalSatisfied(c, assignment, info) {
  return evalPredicate(c.predicate, assignment, info);
}
function isAssignmentValid(model, assignment, info) {
  for (const c of model.constraints) {
    if (!isConstraintSatisfied(c, assignment, info)) return false;
  }
  return true;
}
function isPartiallyForbidden(model, partial, info, options = {}) {
  const limit = options.limit ?? DEFAULT_ENUMERATION_LIMIT;
  for (const name of Object.keys(partial)) {
    if (!info.byName.has(name)) {
      return failure("unknown-factor", `Unknown factor: ${name}`);
    }
  }
  if (info.factors.some((f) => f.levels.length === 0)) {
    return failure("invalid-model", "Model contains a factor with no levels");
  }
  const partialKeys = new Set(Object.keys(partial));
  const { relevantFactorNames, relevantConstraints } = relevantSubmodel(
    model,
    partialKeys
  );
  if (relevantConstraints.length === 0) {
    return { ok: true, value: false };
  }
  const freeFactors = info.factors.filter(
    (f) => relevantFactorNames.has(f.name) && !partialKeys.has(f.name)
  );
  let total = 1;
  for (const f of freeFactors) {
    total *= f.levels.length;
    if (total > limit) {
      return failure(
        "too-large",
        `Enumeration would exceed limit (${limit}); reduce factor cardinalities or N`
      );
    }
  }
  let foundValid = false;
  enumerateExtensions(freeFactors, 0, { ...partial }, (assignment) => {
    for (const c of relevantConstraints) {
      if (!isConstraintSatisfied(c, assignment, info)) return true;
    }
    foundValid = true;
    return false;
  });
  return { ok: true, value: !foundValid };
}
function relevantSubmodel(model, seed) {
  const constraintFactors = model.constraints.map(
    (c) => factorsTouched(c)
  );
  const reach = new Set(seed);
  let changed = true;
  while (changed) {
    changed = false;
    for (const fs of constraintFactors) {
      let touches = false;
      for (const f of fs) {
        if (reach.has(f)) {
          touches = true;
          break;
        }
      }
      if (!touches) continue;
      for (const f of fs) {
        if (!reach.has(f)) {
          reach.add(f);
          changed = true;
        }
      }
    }
  }
  const relevantConstraints = [];
  for (let i = 0; i < model.constraints.length; i++) {
    const fs = constraintFactors[i];
    if (fs.size === 0) continue;
    let touches = false;
    for (const f of fs) {
      if (reach.has(f)) {
        touches = true;
        break;
      }
    }
    if (touches) relevantConstraints.push(model.constraints[i]);
  }
  return { relevantFactorNames: reach, relevantConstraints };
}
function factorsTouched(c) {
  const set = /* @__PURE__ */ new Set();
  const visit = (p) => {
    switch (p.type) {
      case "or":
      case "and":
        visit(p.left);
        visit(p.right);
        return;
      case "not":
        visit(p.operand);
        return;
      case "comparison":
        set.add(p.left.name);
        if (p.right.type === "paramRef") set.add(p.right.name);
        return;
      case "in":
        set.add(p.left.name);
        return;
    }
  };
  if (c.type === "if") {
    visit(c.condition);
    visit(c.then);
    if (c.else) visit(c.else);
  } else {
    visit(c.predicate);
  }
  return set;
}
function enumerateExtensions(factors, index, current, visit) {
  if (index === factors.length) {
    return visit(current);
  }
  const factor = factors[index];
  for (const lv of factor.levels) {
    current[factor.name] = lv;
    const cont = enumerateExtensions(factors, index + 1, current, visit);
    if (!cont) {
      delete current[factor.name];
      return false;
    }
  }
  delete current[factor.name];
  return true;
}
function computeForbiddenSlice(model, factors, options = {}) {
  const info = buildTypeInfo(model);
  for (const name of factors) {
    if (!info.byName.has(name)) {
      return failure("unknown-factor", `Unknown factor: ${name}`);
    }
  }
  const limit = options.limit ?? DEFAULT_ENUMERATION_LIMIT;
  let sliceSize = 1;
  for (const name of factors) {
    sliceSize *= info.byName.get(name).levels.length;
    if (sliceSize > limit) {
      return failure(
        "too-large",
        `Slice cardinality (${sliceSize}+) exceeds limit (${limit})`
      );
    }
  }
  const cells = [];
  const sliceFactorInfos = factors.map((n) => info.byName.get(n));
  let aborted = null;
  enumerateExtensions(sliceFactorInfos, 0, {}, (assignment) => {
    const partial = { ...assignment };
    const result = isPartiallyForbidden(model, partial, info, options);
    if (!result.ok) {
      aborted = result;
      return false;
    }
    cells.push({ assignment: partial, forbidden: result.value });
    return true;
  });
  if (aborted) return aborted;
  return { ok: true, value: { cells, factors } };
}
function failure(reason, message) {
  return { ok: false, reason, message };
}

// src/engines/dsl/extractSlices.ts
function extractSuggestedSlices(model) {
  const slices = [];
  const seen = /* @__PURE__ */ new Set();
  const emit = (conditions, constrained) => {
    if (conditions.length === 0 || !constrained) return;
    const key = [...conditions].sort().join("|") + "::" + constrained;
    if (seen.has(key)) return;
    seen.add(key);
    slices.push({
      conditionFactors: [...conditions],
      constrainedFactor: constrained
    });
  };
  for (const c of model.constraints) {
    extractFromConstraint(c, emit);
  }
  const components = connectedComponents(model);
  for (const component of components) {
    if (component.length < 3) continue;
    for (const constrained of component) {
      const conditions = component.filter((f) => f !== constrained);
      emit(conditions, constrained);
    }
  }
  return slices;
}
function connectedComponents(model) {
  const parent = /* @__PURE__ */ new Map();
  for (const p of model.parameters) parent.set(p.name, p.name);
  const find = (x) => {
    let cur = x;
    let next = parent.get(cur) ?? cur;
    while (next !== cur) {
      cur = next;
      next = parent.get(cur) ?? cur;
    }
    return cur;
  };
  const union = (a, b) => {
    const ra = find(a);
    const rb = find(b);
    if (ra !== rb) parent.set(ra, rb);
  };
  for (const c of model.constraints) {
    const factors = factorsInConstraint(c);
    for (let i = 1; i < factors.length; i++) {
      union(factors[0], factors[i]);
    }
  }
  const groups = /* @__PURE__ */ new Map();
  for (const p of model.parameters) {
    if (!parent.has(p.name)) continue;
    const root = find(p.name);
    let g = groups.get(root);
    if (!g) {
      g = [];
      groups.set(root, g);
    }
    g.push(p.name);
  }
  return Array.from(groups.values()).filter((g) => g.length >= 2);
}
function factorsInConstraint(c) {
  const set = /* @__PURE__ */ new Set();
  const visit = (name) => {
    set.add(name);
  };
  if (c.type === "if") {
    walk(c.condition, visit);
    walk(c.then, visit);
    if (c.else) walk(c.else, visit);
  } else {
    walk(c.predicate, visit);
  }
  return Array.from(set);
}
function extractFromConstraint(c, emit) {
  if (c.type === "if") {
    const condFactors = orderedFactors(c.condition);
    const thenFactors = orderedFactors(c.then);
    const elseFactors = c.else ? orderedFactors(c.else) : [];
    const condSet = new Set(condFactors);
    const targets = [];
    for (const f of thenFactors) {
      if (!condSet.has(f) && !targets.includes(f)) targets.push(f);
    }
    for (const f of elseFactors) {
      if (!condSet.has(f) && !targets.includes(f)) targets.push(f);
    }
    if (targets.length > 0) {
      for (const t of targets) emit(condFactors, t);
      return;
    }
    for (const f of condSet) {
      const others = condFactors.filter((x) => x !== f);
      if (others.length > 0) emit(others, f);
    }
    return;
  }
  const factors = orderedFactors(c.predicate);
  if (factors.length < 2) return;
  const constrained = factors[factors.length - 1];
  const conditions = factors.slice(0, -1);
  emit(conditions, constrained);
}
function orderedFactors(p) {
  const ordered = [];
  const seen = /* @__PURE__ */ new Set();
  const visit = (name) => {
    if (seen.has(name)) return;
    seen.add(name);
    ordered.push(name);
  };
  walk(p, visit);
  return ordered;
}
function walk(p, visit) {
  switch (p.type) {
    case "or":
    case "and":
      walk(p.left, visit);
      walk(p.right, visit);
      return;
    case "not":
      walk(p.operand, visit);
      return;
    case "comparison":
      visit(p.left.name);
      if (p.right.type === "paramRef") visit(p.right.name);
      return;
    case "in":
      visit(p.left.name);
      return;
  }
}

// src/engines/dsl/decisionTable.ts
var DECISION_TABLE_LIMIT = 4096;
var ZERO_RANGE = {
  start: { line: 1, column: 1, offset: 0 },
  end: { line: 1, column: 1, offset: 0 }
};
function generateDecisionTable(model, options = {}) {
  const limit = options.limit ?? DECISION_TABLE_LIMIT;
  const structural = structuralDiagnostics(model);
  if (structural.length > 0) {
    return { ok: false, reason: "invalid-model", diagnostics: structural };
  }
  const info = buildTypeInfo(model);
  const columns = info.factors.map((f) => f.name);
  let count = 1;
  for (const f of info.factors) count *= f.levels.length;
  if (count > limit) {
    return { ok: false, reason: "too-large", count, limit };
  }
  const rows = [];
  const levelLists = info.factors.map((f) => f.levels);
  const cursor = new Array(info.factors.length).fill(0);
  for (let produced = 0; produced < count; produced++) {
    const assignment = {};
    const values = new Array(info.factors.length);
    for (let i = 0; i < info.factors.length; i++) {
      const value = levelLists[i][cursor[i]];
      assignment[columns[i]] = value;
      values[i] = String(value);
    }
    rows.push({ values, forbidden: !isAssignmentValid(model, assignment, info) });
    advance(cursor, levelLists);
  }
  return { ok: true, columns, rows };
}
function advance(cursor, levelLists) {
  for (let i = cursor.length - 1; i >= 0; i--) {
    cursor[i]++;
    if (cursor[i] < levelLists[i].length) return;
    cursor[i] = 0;
  }
}
function structuralDiagnostics(model) {
  const diagnostics = [];
  if (model.parameters.length === 0) {
    diagnostics.push({
      severity: "error",
      kind: "syntax",
      message: "Model declares no factors; a decision table needs at least one.",
      range: ZERO_RANGE
    });
    return diagnostics;
  }
  for (const p of model.parameters) {
    if (p.levels.length === 0) {
      diagnostics.push({
        severity: "error",
        kind: "syntax",
        message: `Factor "${p.name}" has no levels.`,
        range: p.nameRange
      });
    }
  }
  return diagnostics;
}
export {
  DECISION_TABLE_LIMIT,
  DEFAULT_ENUMERATION_LIMIT,
  MASK_LEVEL,
  buildTypeInfo,
  computeForbiddenSlice,
  evalPredicate,
  extractSuggestedSlices,
  generateDecisionTable,
  isAssignmentValid,
  isConstraintSatisfied,
  isMaskLevel,
  isMaskLevelNode,
  isPartiallyForbidden,
  lex,
  parse,
  validateModel
};
